name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
  release:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target_os: linux
            target_platform: linux_amd64
            compiler: gcc
            archive: ar

          - os: ubuntu-24.04-arm
            target_os: linux
            target_platform: linux_arm64
            compiler: gcc
            archive: ar

          - os: ubuntu-latest
            target_os: linux
            target_platform: linux_i386
            compiler: gcc
            archive: ar

          - os: windows-latest
            msvc_arch: x64
            target_os: windows
            target_platform: win64_msvc16
            compiler: cl
            archive: lib

          - os: windows-11-arm
            msvc_arch: arm64
            target_os: windows
            target_platform: winarm64_msvc16
            compiler: cl
            archive: lib

          - os: windows-latest
            msvc_arch: x86
            target_os: windows
            target_platform: win32_msvc16
            compiler: cl
            archive: lib

          - os: macos-latest
            target_os: macos
            target_platform: macos
            compiler: clang
            archive: ar

          - os: ubuntu-latest
            target_os: wasm
            target_platform: webassembly
            compiler: emcc
            archive: emar

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup windows
        if: matrix.target_os == 'windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Setup linux
        if: matrix.target_os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libgl1-mesa-dev \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          libxcursor-dev \
          libxinerama-dev

      - name: Setup wasm
        if: matrix.target_os == 'wasm'
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 5.0.3
          actions-cache-folder: 'emsdk-cache'

      - name: Build
        run: make TARGET_OS=${{ matrix.target_os }} TARGET_PLATFORM=${{ matrix.target_platform }} CC=${{ matrix.compiler }} AR=${{ matrix.archive }}

      - name: Package artifact
        shell: bash
        run: |
          tar -a -c -f raygui-5.0.0_${{ matrix.target_platform }}.zip -C bin ${{ matrix.target_platform }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target_platform }}
          path: ${{ matrix.target_platform }}.zip